### ISSUE TITLE
May I request a deployment document for Sundial?

### ISSUE THREAD

**Issue by llheaven** [yxymit/Sundial#1]
Hi, I personally want to learn sundial very much. I want to deploy sundial on multiple servers, but I don't know how to configure each node and the role of each node in the cluster. May I request a deployment document for Sundial? My email address：seilwang@163.com.  Thank you very much.

**Comment by yxymit** [comment]
Hi, thanks for your interest in the code. Configuration instructions will be added to the README file in the next few days. Stay tuned.

**Comment by yxymit** [comment]
Configuration instructions are added to README. Please let me know if you have more questions.
