### ISSUE TITLE
Assertion fails during rundb

### ISSUE THREAD

**Issue by masabahmad** [yxymit/Sundial#2]
Hi,

I am running Sundial on a 64-bit Ubuntu system. It builds fine (though I had to install jemalloc). However doing `./rundb` gives an error:

```
/home/masahmad/Sundial# ./rundb
Connection Test PASS!
mem_allocator initialized!
workload initialized!
Node 0 sync done!
running on single node
rundb: system/txn.cpp:283: RC TxnManager::execute(bool): Assertion `rc == RCOK || rc == ABORT' failed.
rundb: system/txn.cpp:283: RC TxnManager::execute(bool): Assertion `rc == RCOK || rc == ABORT' failed.
Aborted (core dumped)
```

Any idea on why this may be happening? Its happening regardless of any change made to the config.h file.

Thanks
Masab

**Comment by yxymit** [comment]
Hi Masab, 

Thanks for pointing this out. This is due to a bug that I have just fixed. 

Best,
Xiangyao

**Comment by masabahmad** [comment]
Thank you Xiangyao. It is working now.
